config/routes.rb
Rails.application.routes.draw do

  root 'courses#index'
  # get 'courses/new', to: 'courses#new'
  get 'about', to: 'pages#about'
  resources :courses, except: [:index]
  resources :users

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'course_enroll', to: 'user_courses#create'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  validates :short_name, presence: true, length: { minimum: 5, maximum: 10} 
  validates :name, presence: true, length: {minimum: 3, maximum: 20}
  validates :description, presence: true, length: {minimum: 10, maximum: 500}
  has_many :user_courses
  has_many :users, through: :user_courses
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  validates :name, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  has_many :user_courses
  has_many :courses, through: :user_courses
end

app/models/user_course.rb
class UserCourse < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :require_user


    # Metody do sprawdzenia logowania sa tworzone w ApplicationController,
    # poniewaz dzieki temu beda dostepne TYLKO w kontrolerach, mozna byloby je 
    # rowniez wprowadzic do helpers -> application_helper, ale bylyby dost-
    # epne tylko dla wszystkich widokow. 
    # Obecnie te metody sa dostpene TYLKO w kontrolerach.

    helper_method :current_user, :logged_in?

    # powyzsze helper_method umozliwia dostep tych metod rowniez dla widokow

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    # Powyzsza metoda:
    # TRZECI CZLON: if a session variable is set
    # DRUGI CZLON: then it finds that user based on the user_id in the session
    # (from the session hash)
    # ---
    # it grabs a user_id and it finds a user based on that
    # PIERWSZY CZLON: and we're assigning it to this @current_user variable.
    # we can use this to see if there is a logged in user.

    # metoda current_user ->  I can always refer to my current user, 
    #                         and if I have a current user, it gets 
    #                         me the current user at all times.

    # modyfikacja polegajaca na dopisaniu || nazywa sie memorisation,
    # pozwala ona zapamietac zmienna current_user i dzieki temu nie trzeba caly czas
    # tworzy zapytania do bazy. 
    #
    # We are quaring the DB to user class finding in the user table based on user_id.
    # We are grabbing that particular user object.
    # Now, I don't want to keep hitting the database again and again if 
    # I already have @current_user as an object.

    # Two pipes equal, and this is called memorisation, this will only perform this query 
    # query jest po znaku =
    # if my @current_user object does not exist and if my @current_user object exists,
    # then it does not perform this.
    # It simply returns this current_user object.
    # So I'm skipping an entire database lookup, which is great.
    # A table lookup is costly, so I don't have to perform this.

    def logged_in?
        !!current_user
    end

    # w metodzie logged_in? zmieniamy current_user na boolean true/false 
    # i dzieki temu sprawdzamy, czy current_user jest true or false
    # czyli czy jest zalogowany, czy nie.

    def require_user
      if !logged_in?
        flash[:notice] = "You must be logged in to perform that action"
        redirect_to login_path
      end
    end
    
    # metoda wymagajaca zalogowania

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  skip_before_action :require_user

  def index
    @courses = Course.all
  end

  def new

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :require_user
  
  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    skip_before_action :require_user, only: [:new, :create]

    def new
        
    end

    def create
        user = User.find_by(email: params[:session][:email])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "You have successfully logged in"
            redirect_to user    
        else
            flash.now[:alert] = "Somthing was wrong with your loggin information"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "You have successfully logged out"
        redirect_to root_path
    end

    
end

app/controllers/user_courses_controller.rb
class UserCoursesController < ApplicationController
  
  def create
    course_to_add = Course.find(params[:course_id]) #na podstawie otrzymanego id kursu przypisujemy ten kurs do zmiennej 
    unless current_user.courses.include?(course_to_add) #i sprawdzamy czy dany kurs jest przypisany do danego usera
      UserCourse.create(course: course_to_add, user: current_user)  #jezeli nie jest, tworzymy association pomiedzy course i user tak jak w consoli
      flash[:notice] = "You have successfully enrolled in #{course_to_add.name}"
      redirect_to current_user
    else
      flash[:notice] = "Sonething was wrong with your enrollment"
      redirect_to root_path
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :require_user, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_same_user, only: [:edit, :update]
  
  def index
    @users = User.all
  end

  def show
    
  end

  def new
    @user = User.new
  end

  def edit
    
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the UnivApp #{@user.name}. User was created successfully."
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    
    if @user.update(user_params)
      flash[:notice] = "Your profile was updated successfully"
      redirect_to @user
    else
      render 'edit'
    end
  end



  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:notice] = "You can olny edit your own profile"
      redirect_to user_path(current_user) 
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def session_link
    if (logged_in?)
      link_to "Logout", logout_path, data: { turbo_method: :delete}
    else
      link_to "Login", login_path
    end
  end

  def students_index
    if logged_in?
      link_to "Students", users_path
    end
  end

end

app/views/courses/index.html.erb
<div class="row">
  <h3 class= 'center-align'>Course Listing</h3>
</div>


<div class="row">
  <% @courses.each do |course| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= course.short_name %>: <%= course.name %></span>
          <p><%= course.description%></p>
        </div>
        <div class="card-action">
          <% if logged_in? && !(current_user.courses.include?(course))%>
            <%= link_to "Enroll", course_enroll_path(course_id: course.id), data: {turbo_method: :post} %>
          <% end %>
          <%# powyzszy link_to zaciaga id konkretnego kursu i poprzez klikniecie odnosnika przerzuca id do controllera %>
          <a href="#">This is a link</a>
        </div>
      </div>
    </div>
  <%end %>
</div>

app/views/courses/new.html.erb
<h1>This is the new course page</h1>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">BetterJSOS!</h5>
        <p class="grey-text text-lighten-4">The future of oldJSOS</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Contact us!</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2023 BetterJSOS!
    <a class="grey-text text-lighten-4 right" href="#!">About</a>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<header>

  <ul id="dropdown1" class="dropdown-content">
    <li><%=session_link%></li>
    <li class="divider"></li>
    <li><a href="#!">two</a></li>
    <li class="divider"></li>
    <li><a href="#!">three</a></li>
  </ul>
  <ul id="dropdown2" class="dropdown-content">
    <li><%=session_link%></li>
    <li class="divider"></li>
    <li><a href="#!">two</a></li>
    <li class="divider"></li>
    <li><a href="#!">three</a></li>
  </ul>

  <nav>
    <div class="container">
      <div class="nav-wrapper">
        <%= link_to "BetterJSOS!", root_path, :class => "brand-logo right"%>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li><%=link_to "Courses", root_path%></li>
          <% if logged_in?%>
            <li><%= link_to "Students", users_path%></li>
          <%end%>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
        <ul class="sidenav" id="mobile-demo">
          <li><%=link_to "Courses", root_path%></li>
          <li><%= students_index %></li>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
      </div>
    </div>
  </nav>

  <% flash.each do |key, message| %>
    <div class="container">
      <div class="row">
        <div class="col s12 m12 l12">
          <div class="card-panel green lighten-2" id="fade-out-target">
            <span class="white-text">
              <%= message %>
            </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BetterJSOS</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render 'layouts/navbar'%>

    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <%= render 'layouts/footer'%>

  </body>
  
</html>

app/views/layouts/messages.html.slim
.container
    = flash.each do |name, msg|
        

app/views/pages/about.html.erb
<h1>This is the temp about page</h1>

app/views/shared/_errors.html.slim
- if obj.errors.any?
  .container
    .row
      .col.s12.m12.l12
        .card-panel.red.lighten-2
          span.white-text
            strong
              = pluralize(@user.errors.count, "error")
            |  prohibited your profile from being created: 
            ul
              - @user.errors.full_messages.each do |message|
                li
                  = message

app/views/users/_form.html.slim
.container
  .row.center
    .col.s12.m12.l12
      .card-panel
        h3 
          .header   
            = @user.new_record? ? "Sign up" : "Edit Your Profile"
              
        .row
          =form_with(model: @user, data: {turbo: false}, :class => "col s12", local: true) do |f|
            .row
              .input-field.col.s12 
                =f.text_field :name
                =f.label :name, :class => "active"
            .row
              .input-field.col.s12 
                =f.email_field :email
                =f.label :email, :class => "active"
            .row
              .input-field.col.s12 
                =f.password_field :password
                =f.label :password, :class => "active"
            .row
              .input-field.col.s12 
                =f.password_field :password_confirmation
                =f.label :password_confirmation, :class => "active"
            .row 
              .input-field.col.s12 
                 =f.button(@user.new_record? ? '<i class="material-icons right">arrow_forward</i>Sign up!'.html_safe : '<i class="material-icons right">arrow_forward</i>Update!'.html_safe, :class => "waves-effect waves-light btn")

app/views/users/edit.html.slim
= render 'shared/errors', obj: @user
= render 'form'

app/views/users/index.html.erb
<div class="row">
  <h3 class= 'center-align'>Users Directory</h3>
</div>


<div class="row">
  <% @users.each do |user| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= user.name %></span>
          <p><%= user.email %></p>
          <p>Course Enrollments: NONE</p>
        </div>
        <div class="card-action">
          <a href="#">Profile view</a>
        </div>
      </div>
    </div>
  <%end %>
</div>

app/views/users/index.html.slim
.row
  h3.center-align
    | Users Directory
.row
  - @users.each do |user|
    .col.s6.m6
      .card.blue-grey.darken-1
        .card-content.white-text
          span.card-title
            = user.name
          p
            = user.email
          p
            | Course Enrollments: NONE
        .card-action
          =link_to "View Profile", user_path(user)

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div class="container">
    <div class="row">
      <div class="col s12 m12 l12">
        <div class="card-panel red lighten-2">
          <span class="white-text">
            <strong><%= pluralize(@user.errors.count, "error") %></strong>
            prohibited your profile from being created:
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="container">
  <div class="row center">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header">Sign up!</h3>
          <div class="row">
            <%= form_with(model: @user, data: {turbo: false}, :class => "col s12", local: true) do |f| %>
              <div class="row">
                <div class="input-field col s12">
                  <%= f.text_field :name %>
                  <%= f.label :name %>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  <%= f.email_field :email %>
                  <%= f.label :email %>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  <%= f.submit "Submit", :class => "waves-effect waves-light btn-small"%>
                <div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.slim
= render 'shared/errors', obj: @user
= render 'form'

app/views/users/show.html.slim
.row
    h3.center-align
       =@user.name
       |'s Profile
.row
  .col.s6.m6
    .card.blue-grey.darken-1
      .card-content.white-text
          span.card-title
            = @user.name
          p
          = @user.email
          p
          | Course Enrollments:
          - if @user.courses.empty?
            |  None 
          - else
            ul
              - @user.courses.each do |course|
                li
                  = course.name

    - if current_user == @user                
      = link_to '<i class="material-icons right">create</i>"Edit your profile"'.html_safe,\
          edit_user_path(@user), :class => "waves-effect waves-light btn" 
          